# Mac OS X uses path_helper and /etc/paths.d to preload PATH, clear it out first
if [ -x /usr/libexec/path_helper ]; then
    PATH=''
    eval `/usr/libexec/path_helper -s`
fi

# ChefDK - add path to ChefDK ahead of /usr/bin so as to get ChefDK ruby and
# gem
# export PATH=/opt/chefdk/bin:/opt/chefdk/embedded/bin:$HOME/.gem/ruby/2.1.5/bin:$PATH

# Put Homebrew at the head of the path
# /usr/local/bin is also first in /etc/paths
export PATH="/usr/local/bin:$PATH"


# if rbenv is present, configure it for use
# if which rbenv &> /dev/null; then
if [ -d $HOME/.rbenv ]; then
    # Put the rbenv entry at the front of the line
    export PATH="$HOME/.rbenv/bin:$PATH"

    # enable shims and auto-completion
    eval "$(rbenv init -)"
fi

# Add RVM to PATH for scripting, if rvm is present
if which rvm-prompt &> /dev/null; then
    export PATH=$HOME/.rvm/bin:$PATH
fi

export GOPATH=/usr/local/Cellar/go/1.8.3
export GOBIN=$GOPATH/bin
export PATH=$PATH:$GOBIN


export SPARK_PATH=~/Tools/spark-1.6.0-bin-hadoop2.6

export PATH=$SPARK_PATH/bin:$PATH

export PYSPARK_DRIVER_PYTHON="jupyter"

export PYSPARK_DRIVER_PYTHON_OPTS="notebook"

alias snotebook='$SPARK_PATH/bin/pyspark --masterlocal[2]'

export JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk-9.0.1.jdk/Contents/Home/
export PATH=$JAVA_HOME/bin:$PATH

